const initialProducts = [
    {
        "id": "001",
        "name": "DELL Latitude 3550 Laptop, 15\"inch",
        "description": "<p>15.6\" FHD (1920x1080) Non-Touch, AG, IPS, 250 nits, FHD Cam, WLAN, Intel® Core™ Ultra 5 125U (12 MB cache, 12 cores, 14 threads, up to 4.3 GHz Turbo) , Windows 11 Pro , Intel® Graphics , 16 GB DDR5 , 512 GB SSD ,3yrs pro support NBD onsite service.</p>",
        "collection": "Laptop",
        "price": 7399,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 7000,
        "brand": "DELL"
    },
    {
        "id": "002",
        "name": "Latitude 3450 Laptop, 14\"inch",
        "description": "<p>14.0\" FHD (1920x1080) Non-Touch, AG, IPS, 250 nits, FHD Cam, WLAN ,13th Gen Intel® Core™ i5-1335U, Windows 11 Pro , Intel® Iris® Xe or UHD Graphics , 16 GB DDR5 , 512 GB SSD ,3yrs Prosupport NBD onsite service.</p>",
        "collection": "Laptop",
        "price": 7099,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 6799,
        "brand": "DELL"
    },
    {
        "id": "003",
        "name": "OptiPlex 7020Micro Form Factor Plus",
        "description": "<p>Intel® Core™ i7 14700T vPro®, Windows 11 Pro , 16 GB DDR5 , 512 GB SSD,3yrs prosupport NBD onsite serivce.</p>",
        "collection": "Desktop",
        "price": 7660,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 7350,
        "brand": "DELL"
    },
    {
        "id": "004",
        "name": "OptiPlex 7020Micro Form Factor",
        "description": "<p>Intel® Core™ i5 14500T vPro®, Windows 11 Pro , 16 GB DDR5 , 512 GB SSD ,3yrs pro support NBD onsite service.</p>",
        "collection": "Desktop",
        "price": 5890,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 5600,
        "brand": "DELL"
    },
    {
        "id": "005",
        "name": "OptiPlex Small Form Factor Plus",
        "description": "<p>Intel® Core™ i7 14700 vPro®, Windows 11 Pro , Intel® Graphics , 16 GB DDR5 , 512 GB SSD ,3yrs prosupport NBD onsite serivce.</p>",
        "collection": "Desktop",
        "price": 7780,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 7400,
        "brand": "DELL"
    },
    {
        "id": "006",
        "name": "DELL Optpilex7020SFF",
        "description": "<p>Intel® Core™ i5 14500 vPro®, Windows 11 Pro , Intel® Graphics , 16 GB DDR5 , 512 GB SSD ,3Yrs Prosupport NBD onsite service.</p>",
        "collection": "Desktop",
        "price": 5600,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 5300,
        "brand": "DELL"
    },
    {
        "id": "007",
        "name": "DELL Optpilex7020MT plus",
        "description": "<p>Intel® Core™ i7 14700 vPro®, 16 GB DDR5 , 512 GB 固態硬碟 , Intel® 顯示晶片 , Windows 11 專業版 ,3yrs Prosupport NBD on site service.</p>",
        "collection": "Desktop",
        "price": 7600,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 7380,
        "brand": "DELL"
    },
    {
        "id": "008",
        "name": "DELL Optpilex7020MT",
        "description": "<p>Intel® Core™ i5 14500 vPro, 16 GB: 1 x 16 GB, DDR5 , M.2 2230 512GB PCIe NVMe SSD Class 25 , Intel® 顯示卡 , Windows 11 專業版, 英文, 簡體中文, 繁体中文 ,3YRS ProSupport NBD onsite service.</p>",
        "collection": "Desktop",
        "price": 6050,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 5750,
        "brand": "DELL"
    },
    {
        "id": "009",
        "name": "Apple MBA 15.3 SPG/10C GPU/8GB/512GB-ITP",
        "description": "<p>MBA 15.3 SPG/10C GPU/8GB/512GB-ITP</p>",
        "collection": "Laptop",
        "price": 11999,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 11459,
        "brand": "APPLE"
    },
    {
        "id": "010",
        "name": "13-inch iPad Air Wi-Fi 128GB - Space Grey",
        "description": "<p>13-inch iPad Air Wi-Fi 128GB - Space Grey</p>",
        "collection": "Pad",
        "price": 6299,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 5890,
        "brand": "APPLE"
    },
    {
        "id": "011",
        "name": "10.2-inch iPad Wi-Fi 64GB - Silver",
        "description": "<p>10.2-inch iPad Wi-Fi 64GB - Silver</p>",
        "collection": "Pad",
        "price": 2299,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 2207,
        "brand": "Apple"
    },
    {
        "id": "012",
        "name": "Surface Pro 9",
        "description": "<p>Pro 9 i7/16/256 Win11 Pro MAYA / &nbsp;FOREST / GRAPHITE /PLATINUM&nbsp;</p>",
        "collection": "Microsoft",
        "price": 13988,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 400,
        "inventory": "InStock",
        "cost": 12600,
        "brand": "Microsoft"
    },
    {
        "id": "013",
        "name": "Surface Pro 9",
        "description": "<p>Pro 9 i5/16/256 Win11 Pro PLATINUM / GRAPHITE</p>",
        "collection": "Microsoft",
        "price": 12788,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 400,
        "inventory": "InStock",
        "cost": 11480,
        "brand": "Microsoft"
    },
    {
        "id": "014",
        "name": "Surface Pro 9",
        "description": "<p>Pro 9 i5/8/256 Win11 Pro PLATINUM / GRAPHITE</p>",
        "collection": "Microsoft",
        "price": 10688,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 300,
        "inventory": "InStock",
        "cost": 9580,
        "brand": "Microsoft"
    },
    {
        "id": "015",
        "name": "Microsoft  Office 2021 OEM  English",
        "description": "<p>Office Home and Business 2021 English Greater China DM Medialess</p><p>Part#116JJ75</p>",
        "collection": "Microsoft",
        "price": 1999,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 1780,
        "brand": "Microsoft"
    },
    {
        "id": "016",
        "name": "Microsoft  Office 2021 OEM C-Thinese",
        "description": "<p>Office Home and Business 2021 ChnTrad Greater China DM Medialess&nbsp;</p><p>Part#116JJ74</p>",
        "collection": "Microsoft",
        "price": 1999,
        "visible": true,
        "discountMode": "PERCENT",
        "discountValue": 0,
        "inventory": "InStock",
        "cost": 1780,
        "brand": "Microsoft"
    },
    {
        "id": "017",
        "name": "Lenovo ThinkCentre Neo 50s Gen 3",
        "description": "<p>Lenovo ThinkCentre Neo 50s Gen 3, B660 Chipset, Intel Core i5-12500, 8GB DDR4-3200 UDIMM, 512GB M.2 PCIe G4 SSD, No ODD, VGA+HDMI+DP, TC USB KB/Mouse, No Vertical Stand, Internal Speaker, 260W PSU, W11P DG W10P, 3 Years On-site Warranty</p>",
        "collection": "Desktop",
        "price": 5899,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 304,
        "inventory": "InStock",
        "cost": 5100,
        "brand": "Lenovo"
    },
    {
        "id": "018",
        "name": "HP 280Pro G9 SFF",
        "description": "<p>HP 280Pro G9 SFF, sku：6N135PA</p><p>HP Pro SFF 280 G9, H670 Chipset, i5-12500, 8GB DDR4, 512GB M.2 PCIe NVMe SSD, ODD, 8*USB Ports, 1*HDMI+1*VGA, Realtek Wifi AC+BT, Eng USB KB/Mouse, W11P DG, 3 Years On-site Wty</p>",
        "collection": "Desktop",
        "price": 6899,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 1099,
        "inventory": "InStock",
        "cost": 5180,
        "brand": "HP"
    },
    {
        "id": "019",
        "name": "APC Smart-UPS C 1500VA LCD 230V",
        "description": "<p>APC Smart-UPS C 1500VA LCD 230V;</p><p>SKU:SMC1500I-2U</p>",
        "collection": "UPS",
        "price": 4900,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 600,
        "inventory": "InStock",
        "cost": 3450,
        "brand": "APC"
    },
    {
        "id": "020",
        "name": "APC Smart-UPS C 1500VA LCD RM 2U 230V",
        "description": "<p>APC Smart-UPS C 1500VA LCD RM 2U 230V;</p><p>SKU:SMC1500I-2U</p>",
        "collection": "UPS",
        "price": 6999,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 1099,
        "inventory": "InStock",
        "cost": 4850,
        "brand": "APC"
    },
    {
        "id": "021",
        "name": "APC Smart-UPS C 1000VA LCD 230V",
        "description": "<p>APC Smart-UPS C 1000VA LCD 230V;</p><p>SKU:SMC1000I</p>",
        "collection": "UPS",
        "price": 3600,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 400,
        "inventory": "InStock",
        "cost": 2480,
        "brand": "APC"
    },
    {
        "id": "022",
        "name": "APC Smart-UPS C 1000VA LCD RM 2U 230V",
        "description": "<p>APC Smart-UPS C 1000VA LCD RM 2U 230V</p><p>SKU:SMC1000I-2U</p>",
        "collection": "UPS",
        "price": 4500,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 600,
        "inventory": "InStock",
        "cost": 2970,
        "brand": "APC"
    },
    {
        "id": "023",
        "name": "Lenovo ThinkCentre M70s G3",
        "description": "<p>Lenovo ThinkCentre M70s G3, Q670 Chipset, Intel Core i5-12500, 8GB DDR4-3200 UDIMM, 512GB M.2 PCIe G4 SSD, No ODD, 1*HDMI+2*DP, TC USB KB/Mouse, No Vertical Stand, Internal Speaker, 260W PSU, W11P DG W10P, 3 Years Premier Support On-site Warranty</p>",
        "collection": "Desktop",
        "price": 6279,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 200,
        "inventory": "InStock",
        "cost": 5590,
        "brand": "Lenovo"
    },
    {
        "id": "024",
        "name": "DELL R450 Server",
        "description": "<p>PowerEdge R450 伺服器:</p><p>2.5吋 機箱 含 最多 8 熱插拔 硬碟, Front PERC;Intel® Xeon® E-2378G 2.8GHz, 16M 快取記憶體, 8C/16T, Turbo (80W), 3200 MT/s;2*16GB RDIMM, 3200MT/s, 雙陣序;&nbsp;RAID 1;2*480GB SSD SATA 讀取密集型 6Gbps 512 2.5吋 熱插拔 AG 碟;雙, 熱插拔, 電源供應器 全 借援 (1+1), 800W,PowerEdge R450 主機板 含 Broadcom 5720 雙 連接埠 1Gb 內建 LOM;iDRAC9, 企業版 15G;&nbsp; No OS, 3yrs&nbsp;ProSupport Plus 與 次營業日到府服務, 36 個月.A11 drop-in/stab-in Combo 滑動式導軌 含 線纜 管理桿</p>",
        "collection": "Server",
        "price": 26480,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 2000,
        "inventory": "InStock",
        "cost": 23000,
        "brand": "DELL"
    },
    {
        "id": "025",
        "name": "ThinkPad X13",
        "description": "<p>ThinkPad X13 G3, Intel Core i7-1260P, 16GB DDR5-On-Board Ram, 512GB PCIe-NVMe G4 SSD, , 13\" WUXGA (1920x1200, W11P DG W10P, 3 Yrs Sealed Battery & Premier NBD Support Warranty</p>",
        "collection": "Laptop",
        "price": 11900,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 2120,
        "inventory": "InStock",
        "cost": 8999,
        "brand": "Lenovo"
    },
    {
        "id": "026",
        "name": "Server  R350",
        "description": "<p>DELL&nbsp;PowerEdge R350 Server:</p><p>Intel® Xeon® E-2378G 2.8GHz, 16M 快取記憶體, 8C/16T, Turbo (80W), 3200 MT/s;2.5吋 機箱 含 最多 8 熱插拔 硬碟, Front PERC,2*16GB UDIMM, 3200MT/s, ECC, 2*1.2TB 硬碟 ISE SAS 12Gbps 10k 512n 2.5吋 熱插拔,Raid 1;雙, 熱插拔, 備援 電源供應器 (1+1), 600W;PowerEdge R350 主機板 含 Broadcom 5720 雙 連接埠 1Gb 內建 LOM, V2;iDRAC9, 企業版 15G;ProSupport 與 次營業日到府服務, 36 個月</p>",
        "collection": "Server",
        "price": 19420,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 1420,
        "inventory": "InStock",
        "cost": 17000,
        "brand": "DELL"
    },
    {
        "id": "027",
        "name": "DELL  Optiplex7010tower",
        "description": "<ul><li><p>第13代 Intel® Core™ i5-13500 (6+8 核/24MB/20T/2.5GHz to 4.8GHz/65W)</p></li><li><p>Windows 11 家用版, 英文, 簡體中文, 繁体中文<br>(Dell Technologies 推薦商務用 Windows 11 專業版)</p></li><li><p>Intel® 整合式顯示卡</p></li><li><p>8 GB, 1 x 8 GB, DDR4</p></li><li><p>M.2 2230 512GB PCIe NVME Class 35 固態碟</p></li><li><p>OptiPlex Tower 7010 含 180W 銅牌 電源供應器, WW</p></li><li><p>基礎到府服務 12 個月</p></li></ul>",
        "collection": "Desktop",
        "price": 4900,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 201,
        "inventory": "InStock",
        "cost": 4400,
        "brand": "DELL"
    },
    {
        "id": "028",
        "name": "DellOptiplex7010towerPlus",
        "description": "<ul><li><p>第13代 Intel® Core™ i7-13700 (8+8 核/30MB/24T/2.1GHz to 5.1GHz/65W)</p></li><li><p>Windows 11 家用版, 英文, 簡體中文, 繁体中文<br>(Dell Technologies 推薦商務用 Windows 11 專業版)</p></li><li><p>Intel® 整合式顯示卡</p></li><li><p>8 GB, 1 x 8 GB, DDR5</p></li><li><p>M.2 2230 512GB PCIe NVME Class 35 固態碟</p></li><li><p>MTX 立式機型</p></li><li><p>連接埠和插槽</p></li><li><p>基礎到府服務 36 個月, 36 個月</p></li></ul>",
        "collection": "Desktop",
        "price": 6980,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 300,
        "inventory": "InStock",
        "cost": 6400,
        "brand": "DELL"
    },
    {
        "id": "029",
        "name": "Latitude7340",
        "description": "<ul><li><p>第13代 Intel® Core™ i7-1355U (12 MB 快取記憶體, 10 核心, 最高睿頻 5.00 GHz Turbo)</p></li><li><p>Windows 11 家用版, 英文, 簡體中文, 繁体中文<br>(Dell Technologies 推薦商務用 Windows 11 專業版)</p></li><li><p>16 GB, LPDDR5, 4800 MT/s, 整合式</p></li><li><p>512GB M.2 PCIe NVMe 固態碟, Class 35</p></li><li><p>Laptop 13.3吋 FHD (1920x1200) AG, 非-觸控, WVA, 250 nits, FHD IR 攝像頭+IP, WLAN, 鋁</p></li><li><p>3yrs&nbsp; NBD</p></li></ul>",
        "collection": "Laptop",
        "price": 11299,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 1000,
        "inventory": "InStock",
        "cost": 9600,
        "brand": "DELL"
    },
    {
        "id": "030",
        "name": "Dell Latitude 5440",
        "description": "<p>第13代 Intel® Core™ i5-1335U</p><p>Windows 11 家用版</p><p>Intel 第13代 Core i5-1335U Trans.,Intel 整合式 顯示卡,TBT4</p><p>8 GB, 1 x 8 GB, DDR4, 3200 MT/s, 單 通道, 非-ECC</p><p>512 GB, M.2, PCIe NVMe, SSD, Class 35</p><p>14.0-吋顯示器 Full HD (1920X1080)</p><p>起始重量：(1.36 公斤)</p>",
        "collection": "Laptop",
        "price": 7680,
        "visible": true,
        "discountMode": "AMOUNT",
        "discountValue": 300,
        "inventory": "InStock",
        "cost": 7000,
        "brand": "DELL"
    }
]; 